version: '3.8'

services:
 api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
        - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      DB_HOST:  ${DB_HOST}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - postgres
 postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - docker-go-postgres:/var/lib/postgresql/data

volumes:
  docker-go-postgres: